### ISSUE TITLE
Using GFPGAN with dream causes black cast over face

### ISSUE THREAD

**Issue by cvar66** [lstein/stable-diffusion#169]
Create an image with a realistic face 
Create it again but now with using -G1 -U2
GFPGAN will add a dark cast to the face that makes the colors and shadows look blackish and very muddy

When I run the original image through GFPGAN directly with default settings, the results are considerably better.

**Comment by blessedcoolant** [comment]
Can you show me some previews? Also can you try to use the value -G0.99 instead of 1 and tell me if the same problem persists.

**Comment by cvar66** [comment]
original
![000230 2352774659](https://user-images.githubusercontent.com/112285161/187098186-69ece2ba-cabb-4a28-901d-ff75956eacdb.png)
using -G1 -U2 ( 0.99 made no difference)
![000231 2352774659](https://user-images.githubusercontent.com/112285161/187098225-ab9252cd-765c-4bfd-ab52-869c73f980ab.png)
Using GFPGAN directly
![000230 2352774659](https://user-images.githubusercontent.com/112285161/187098245-62b559f9-1ce8-40b7-bc12-ba096cc24279.png)

After doing the comparison it seems it not just color that is affected.

**Comment by blessedcoolant** [comment]
> original ![000230 2352774659](https://user-images.githubusercontent.com/112285161/187098186-69ece2ba-cabb-4a28-901d-ff75956eacdb.png) using -G1 -U2 ( 0.99 made no difference) ![000231 2352774659](https://user-images.githubusercontent.com/112285161/187098225-ab9252cd-765c-4bfd-ab52-869c73f980ab.png) Using GFPGAN directly ![000230 2352774659](https://user-images.githubusercontent.com/112285161/187098245-62b559f9-1ce8-40b7-bc12-ba096cc24279.png)
> 
> After doing the comparison it seems it not just color that is affected. Also if the picture is really well lit and bright it is much less noticeable.

This discoloration seemed to have been happening even without today's changes. Let me look and see why that is the case.

**Comment by blessedcoolant** [comment]
Fixed it. This is not an issue with this repo but rather the utils function provided by GFPGAN in itself.

You can go to `utils.py` and change the following code.

Change both bgr2rgb from `True` to `False` and return rgb from `False` to `True`

`cropped_face_t = img2tensor(cropped_face / 255., bgr2rgb=False, float32=True)`
`output = self.gfpgan(cropped_face_t, return_rgb=True)[0]`
`restored_face = tensor2img(output.squeeze(0), rgb2bgr=False, min_max=(-1, 1))`

Let me know if it fixes the issue for you. Did the trick for me.

**Comment by cvar66** [comment]
This didn't work for me. I used the file in your link. When using the command line it looks the same. When using the web version the effects are calculated but are just not applied anymore. Maybe that's why it looked fixed? The starting image was pretty good to start off with.

**Comment by blessedcoolant** [comment]
> This didn't work for me. I used the file in your link. When using the command line it looks the same. When using the web version the effects are calculated but are just not applied anymore.

I've generated more images. The discoloration definitely is fixed on my end with the above changes. I'll wait on others to tell me their experience before exploration more solutions if need be.

**Comment by cvar66** [comment]
hmm OK, I probably mucked something up. I will try it again. Thanks!

**Comment by Ratinod** [comment]
> I'll wait on others to tell me their experience before exploration more solutions if need be.
Yes. This solves the problem, but breaks the standalone GFPGAN work.

**Comment by cvar66** [comment]
OK so this is still not working for me. I think maybe because I initially installed GFPGAN in the stable diffusion folder. This worked until I tried to use it with dream so I just copied the whole GFPGAN folder into my root directly so the links would work. I'm still pretty new to this. Only reason I can think why this isn't working for me.

**Comment by blessedcoolant** [comment]
> OK so this is still not working for me. I think maybe because I initially installed GFPGAN in the stable diffusion folder. This worked until I tried to use it with dream so I just copied the whole GFPGAN folder into my root directly so the links would work. I'm still pretty new to this. Only reason I can think why this isn't working for me.
> 
> I also tried replacing utils.py in both locations

Are you using the 1.3 model of GFPGAN?

**Comment by cvar66** [comment]
OK so I have more info. I was using k_euler_a with this issue. I tried switching to the default sampler and it works like you said. Then I went back to k_euler_a and the problem is back. This is on the command line. When I use the --web option there are no effects applied to the image after it calculates the face fix. Also I am using 1.4

**Comment by blessedcoolant** [comment]
> OK so I have more info. I was using k_euler_a with this issue. I tried switching to the default sampler and it works like you said. Then I went back to k_euler_a and the problem is back. This is on the command line. When I use the --web option there are no effects applied to the image after it calculates the face fix. Also I am using 1.4

There's no 1.4 afaik? The latest version of the model if 1.3 I think. 

The above image I posted is k_euler_a and I've checked with other models. It's fixes it. Can you share the exact prompt with the seed you are generating? I can try that and see if I get discoloration on my end.

The web UI is being updated. There'll be a patch for that. We made a lot of changes to how GFPGAN and scaling works today.

**Comment by cvar66** [comment]
Sorry it's late here. Yes I am using 1.3. I doubled checked the default sampler images and the problem still exists, I just didn't notice because its a bright picture and the cast is not strong.

**Comment by cvar66** [comment]
"Megan Fox low light" -s20 -b1 -W512 -H512 -C7.5 -mk_euler_a -G1.0 -S2352774659

**Comment by blessedcoolant** [comment]
Here's my result. Same prompt. Using the fix I mentioned above.

![000012 2352774659](https://user-images.githubusercontent.com/54517381/187118030-a7e33bdb-2983-4795-af6d-8c4da8755261.png)

**Comment by cvar66** [comment]
OK, so the problem must be on my end somehow. I'll eventually figure it out. I appreciate all your help! Thank you!

**Comment by cvar66** [comment]
I just wanted to add the solution to my issue. I am using Miniconda in Windows. The reason why the fix did not work for me was because dream was calling utility.py from C:\Users\username\.conda\envs\ldm\Lib\site-packages\gfpgan not GFPGAN/gfpgan. After editing the file there everything works perfect now!

**Comment by lstein** [comment]
After replacing/editing util.py, you might want to run "pip install -e ." in the GFPGAN top-level directory. Make sure you do this while the "ldm" conda environment is active. This will synchronize the files in the source directory with the copies in site-packages.

**Comment by thelamedia** [comment]
Any luck on a patch for this yet?  In docker images it's a major pain to get to this file manually.

**Comment by lstein** [comment]
I still don't have an explanation of why changing gfpgan/utils.py in the GFPGAN directory and then doing pip install -e . isn't updating in the site-packages directory. Happy if someone will point in the right direction.

I have sent a PR to the GFPGAN maintainers with the fix. However, this package hasn't been updated in several months and they may not respond quickly.

**Comment by Ratinod** [comment]
This fix still fixes the work of GFPGAN through dream **AND** breaks (black cast over face) the stand-alone work of GFPGAN? Has this fix been tested on a standalone GFPGAN? At the moment I'm using a .bat file for easy file replacement if I need to use just GFPGAN or GFPGAN through dream.

**Comment by K780420** [comment]
😪

**Comment by K780420** [comment]
🫠😱

**Comment by K780420** [comment]
![image](https://user-images.githubusercontent.com/97131332/190504122-86657a21-f275-497b-a392-f6c06751c6a8.jpeg)

**Comment by nh256** [comment]
![Uploading 20231206_165520.jpg…]()
